definitions:
  environment:
    shared_env: &shared_env
      flutter: 3.27.1
      groups:
        - shorebird
        - firebase_credentials
        - google_credentials
      vars:
        FLUTTER_VERSION: 3.27.1
  scripts:
    - &show_version
      name: Version
      script: |
        echo "âž¡ï¸ Using type: $TYPE"
        VERSION=$(grep 'version:' pubspec.yaml | cut -d':' -f2 | tr -d ' ')
        echo "version: $VERSION"
    - &set_local_properties
      name: Set up local.properties
      script: | 
        echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

    - &shorebird_install
      name: Install Shorebird
      script: |
        # Install Shorebird
        curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

        # Add Shorebird to PATH
        echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV
    - &fetch_dependencies
      name: Fetch Dependencies
      script: |
        flutter pub get
    - &ios_signing_code
      name: Set up code signing settings on Xcode project  
      script: |
        xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'


workflows:
    android-release-nonprod:
        name: android-release-nonprod
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          <<: *shared_env
          android_signing:
            - keystore nonprod
        scripts:
          - *show_version
          - *set_local_properties
          - *shorebird_install
          - *fetch_dependencies
          - name: ðŸ™Œ Shorebird Build
            script: |
              shorebird release android --flutter-version="$FLUTTER_VERSION" --artifact=apk --flavor nonprod --target lib/main_nonprod.dart
        artifacts:
          - build/**/outputs/**/*.apk
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
        publishing:
          slack:
            channel: '#app-update'
            notify_on_build_start: true # To receive a notification when a build starts
            notify:
              success: true 
              failure: true
          firebase:
            firebase_service_account: $FIREBASE_SERVICE_ACCOUNT_NONPROD
            android:
              app_id: 1:19616661900:android:b9dcc916a7cafebd0d56a9
              groups:
                - edupluztester
              artifact_type: 'apk'
          # google_play: 
          #   credentials: $PLAY_STORE_SERVICE_ACCOUNT_CREDENTIALS
          #   track: internal
          #   in_app_update_priority: 3


    android-patch-nonprod:
      name: android-patch-nonprod
      max_build_duration: 120
      instance_type: mac_mini_m2
      environment:
        <<: *shared_env
        android_signing:
          - keystore nonprod
      scripts:
          - *show_version
          - *set_local_properties
          - *shorebird_install
          - *fetch_dependencies
          - name: ðŸš€ Shorebird patch 
            script: |
              shorebird patch --platforms=android --flavor nonprod -t lib/main_nonprod.dart
      publishing:
        slack:
          channel: '#app-update'
          notify_on_build_start: true # To receive a notification when a build starts
          notify:
            success: true 
            failure: true

    android-release-prod:
        name: android-release-prod
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          <<: *shared_env
          android_signing:
            - keystore prod
        scripts:
          - *show_version
          - *set_local_properties
          - *shorebird_install
          - *fetch_dependencies
          - name: ðŸ™Œ Shorebird Build
            script: |
              shorebird release android --flutter-version="$FLUTTER_VERSION" --artifact=aab --flavor prod --target lib/main_prod.dart
        artifacts:
          - build/**/outputs/**/*.aab
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
        publishing: 
          slack:
            channel: '#app-update'
            notify_on_build_start: true # To receive a notification when a build starts
            notify:
              success: true 
              failure: true
          google_play: 
            credentials: $PLAY_STORE_SERVICE_ACCOUNT_CREDENTIALS
            track: internal
            in_app_update_priority: 3

    android-patch-prod:
        name: android-patch-prod
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          <<: *shared_env
          android_signing:
            - keystore nonprod
        scripts:
            - *show_version
            - *set_local_properties
            - *shorebird_install
            - *fetch_dependencies
            - name: ðŸš€ Shorebird patch 
              script: |
                shorebird patch android --flavor prod -t lib/main_prod.dart
        publishing:
          slack:
            channel: '#app-update'
            notify_on_build_start: true # To receive a notification when a build starts
            notify:
              success: true 
              failure: true

    ios-release-nonprod:
        name: iOS Release Nonprod
        max_build_duration: 120
        instance_type: mac_mini_m2
        integrations:
          app_store_connect: codemagic App Store API
        environment:
          <<: *shared_env
          ios_signing:
            provisioning_profiles:
              - profile: ios_profile_app_store
                environment_variable: THIS_PROFILE_PATH_ON_DISK
            certificates:
              - certificate: ios_cer_distribution
                environment_variable: THIS_CERTIFICATE_PATH_ON_DISK
        scripts:
            - *show_version
            - *ios_signing_code
            - *shorebird_install
            - *fetch_dependencies
            - name: ðŸ™Œ Shorebird Build
              script: |
                shorebird release ios --flutter-version="$FLUTTER_VERSION" --flavor nonprod  -t lib/main_nonprod.dart -- --export-options-plist=/Users/builder/export_options.plist
        artifacts:
          - build/ios/ipa/*.ipa
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log

        publishing: 
          slack:
            channel: '#app-update'
            notify_on_build_start: true # To receive a notification when a build starts
            notify:
              success: true 
              failure: true

          app_store_connect:
            auth: integration
            submit_to_testflight: true
            expire_build_submitted_for_review: true
            beta_groups: 
              - monster-tester

    ios-patch-ios-nonprod:
        name: iOS Patch Nonprod
        max_build_duration: 120
        instance_type: mac_mini_m2
        integrations:
          app_store_connect: codemagic App Store API
        environment:
          <<: *shared_env
          ios_signing:
            provisioning_profiles:
              - profile: ios_profile_app_store
                environment_variable: THIS_PROFILE_PATH_ON_DISK
            certificates:
              - certificate: ios_cer_distribution
                environment_variable: THIS_CERTIFICATE_PATH_ON_DISK

        scripts:
          - *show_version
          - *ios_signing_code
          - *shorebird_install
          - *fetch_dependencies
          - name: ðŸ™Œ Shorebird Build
            script: |
              shorebird patch ios --flavor nonprod  -t lib/main_nonprod.dart -- --export-options-plist=/Users/builder/export_options.plist
        artifacts:
          - build/ios/ipa/*.ipa
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
        publishing: 
          slack:
            channel: '#app-update'
            notify_on_build_start: true # To receive a notification when a build starts
            notify:
              success: true 
              failure: true

    ios-release-prod:
        name: iOS Release Prod
        max_build_duration: 120
        instance_type: mac_mini_m2
        integrations:
          app_store_connect: codemagic App Store API
        environment:
          <<: *shared_env
          ios_signing:
            provisioning_profiles:
              - profile: ios_profile_app_store_for_production
                environment_variable: THIS_PROFILE_PATH_ON_DISK
            certificates:
              - certificate: ios_cer_distribution
                environment_variable: THIS_CERTIFICATE_PATH_ON_DISK
        scripts:
            - *show_version
            - *ios_signing_code
            - *shorebird_install
            - *fetch_dependencies
            - name: ðŸ™Œ Shorebird Build
              script: |
                shorebird release ios --flutter-version="$FLUTTER_VERSION" --flavor prod  -t lib/main_prod.dart -- --export-options-plist=/Users/builder/export_options.plist
        artifacts:
          - build/ios/ipa/*.ipa
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log

        publishing: 
          slack:
            channel: '#app-update'
            notify_on_build_start: true # To receive a notification when a build starts
            notify:
              success: true 
              failure: true

          app_store_connect:
            auth: integration
            submit_to_testflight: true
            expire_build_submitted_for_review: true
            beta_groups: 
              - monster-tester

    ios-patch-ios-prod:
        name: iOS Patch Prod
        max_build_duration: 120
        instance_type: mac_mini_m2
        integrations:
          app_store_connect: codemagic App Store API
        environment:
          <<: *shared_env
          ios_signing:
            provisioning_profiles:
              - profile: ios_profile_app_store_for_production
                environment_variable: THIS_PROFILE_PATH_ON_DISK
            certificates:
              - certificate: ios_cer_distribution
                environment_variable: THIS_CERTIFICATE_PATH_ON_DISK

        scripts:
          - *show_version
          - *ios_signing_code
          - *shorebird_install
          - *fetch_dependencies
          - name: ðŸ™Œ Shorebird Build
            script: |
              shorebird patch ios --flavor prod  -t lib/main_prod.dart -- --export-options-plist=/Users/builder/export_options.plist
        artifacts:
          - build/ios/ipa/*.ipa
          - build/**/outputs/**/mapping.txt
          - flutter_drive.log
        publishing: 
          slack:
            channel: '#app-update'
            notify_on_build_start: true # To receive a notification when a build starts
            notify:
              success: true 
              failure: true
       
