// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6WUGy9D_3UIStUhyuRlYVlBn_lZwr54c',
    appId: '1:19616661900:android:b9dcc916a7cafebd0d56a9',
    messagingSenderId: '19616661900',
    projectId: 'edupluz-dev',
    storageBucket: 'edupluz-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWnLRjS4m3_VHMoQQZB9PWUn3REH25-uE',
    appId: '1:19616661900:ios:9ef9f16c6441be080d56a9',
    messagingSenderId: '19616661900',
    projectId: 'edupluz-dev',
    storageBucket: 'edupluz-dev.firebasestorage.app',
    androidClientId:
        '19616661900-jn3nldcskbck357apblp2oehfq3ik8qu.apps.googleusercontent.com',
    iosClientId:
        '19616661900-osoklrrte9f4k2t43g8pqtqs8o1o76g4.apps.googleusercontent.com',
    iosBundleId: 'com.edupluz.edupluzapp.nonProd',
  );
}
